CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(64) NOT NULL,
  `PASSWORD` VARCHAR(128) NOT NULL,
  `SALT` VARCHAR(128) NOT NULL,
  `INVALID_LOGIN_COUNT` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
);

INSERT INTO USERS (`EMAIL`, `PASSWORD`, `SALT`, `INVALID_LOGIN_COUNT`) VALUES
  ('admin', '75B09AF8C3DA408696637E7AE8D243D9', '7FC67866A795CE1A61C30D42374E943C', 3);

CREATE TABLE IF NOT EXISTS `LOGIN_ACTIVITY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `IP_ADDRESS` VARCHAR(16) NOT NULL,
  `TIMESTAMP` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES USERS(`ID`)
);

CREATE TABLE IF NOT EXISTS `PERSISTED_FILE_INFO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `FILE_NAME` VARCHAR(64) NOT NULL,
  `FILE_PATH` VARCHAR(128) NOT NULL,
  `IS_PRIVATE` TINYINT(1) NOT NULL,
  `KEY` VARCHAR(128),
  `SALT` VARCHAR(128),
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES USERS(`ID`)
);

CREATE TABLE IF NOT EXISTS `FILE_USER_ASSOCIATION` (
  `USER_ID` INT NOT NULL,
  `FILE_ID` INT NOT NULL,
  PRIMARY KEY(`USER_ID`, `FILE_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES USERS(`ID`),
  FOREIGN KEY (`FILE_ID`) REFERENCES PERSISTED_FILE_INFO(`ID`)
);